
# 使用清华大学的源进行cocoapods
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

target 'LNTools_fyh_Example' do
  pod 'LNTools_fyh', :path => '../LNTools_fyh.podspec'
  pod 'SnapKit'
#  pod 'Kingfisher'

  target 'LNTools_fyh_Tests' do
    inherit! :search_paths
    

  end
end
