use_frameworks!

target 'LNTools_fyh_Example' do
  pod 'LNTools_fyh', :path => '../LNTools_fyh.podspec'
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'LNTools_fyh_Tests' do
    inherit! :search_paths
    

  end
end
